---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-context-path-routing-ingress
  annotations:
    # Ingress Core Settings
    # This specifies whether your LoadBalancer will be internet facing
    alb.ingress.kubernetes.io/scheme: internet-facing # or internal
    # This specifies how to route traffic to pods. You can choose between instance and ip
    alb.ingress.kubernetes.io/target-type: instance # or ip
    # Ingress Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
spec:
  ingressClassName: my-ingress-class-name
  # In Context Path Routing, order of the path rules is important.
  # If you're using "Root Context" i.e. "/*" then
  # add that path rule at the end of all rules.
  rules:
    - http:
        paths:
          - path: /<path-for-nginx-demo-app-1>
            pathType: Prefix
            backend:
              service:
                name: nginx-demo-nodeport-service-1
                port:
                  number: 80
          - path: /<path-for-nginx-demo-app-2>
            pathType: Prefix
            backend:
              service:
                name: nginx-demo-nodeport-service-2
                port:
                  number: 80
